### PR TITLE
Fragpipe params upload

### PR DESCRIPTION
**Pull request by enryH**
- [x] allow uploading more than one file in one go (`st.file_uploader` allows to upload more than one file in multiple steps anyways) for parameter files
- [x] `BufferIO` object reading added for the two FragPipe parameter files
- [x] Add "ppm" to tolerances in parsed output

Questions:
1. Should we plot the parsed parameters in the GUI?

### CODE REVIEW

**Comment by enryH** [comment]
This needs some testing as it might break things (hopefully not though)

**Comment by mlocardpaulet** [comment]
What do you mean by "should we plot the parsed parameters?"

**Comment by mlocardpaulet** [comment]
> This needs some testing as it might break things (hopefully not though)

I'll give it a try.

**Comment by mlocardpaulet** [comment]
When I try the fragpipe .params and .workflow files, there is something a bit weird in the field 'variable_mods':

```
 'variable_mods': '15.9949,M,true,3; 42.0106,[^,true,1; 79.96633,STY,false,3; '
                  '-17.0265,nQnC,false,1; -18.0106,nE,false,1; '
                  '4.025107,K,false,2; 6.020129,R,false,2; 8.014199,K,false,2; '
                  '10.008269,R,false,2; 0.0,site_10,false,1; '
                  '0.0,site_11,false,1; 0.0,site_12,false,1; '
                  '0.0,site_13,false,1; 0.0,site_14,false,1; '
                  '0.0,site_15,false,1; 0.0,site_16,false,1'}
```

But I am not sure that it comes from your script, since it looks a bit off in the fragger.params file that I used (the one in the folder test):
[lines 65-81] 
```
# maximum of 16 mods - amino acid codes, * for any amino acid, [ and ] specifies protein termini, n and c specifies peptide termini
variable_mod_01 = 15.9949 M 3
variable_mod_02 = 42.0106 [^ 1
# variable_mod_03 = 79.96633 STY 3
# variable_mod_04 = -17.0265 nQnC 1
# variable_mod_05 = -18.0106 nE 1
# variable_mod_06 = 4.025107 K 2
# variable_mod_07 = 6.020129 R 2
# variable_mod_08 = 8.014199 K 2
# variable_mod_09 = 10.008269 R 2
# variable_mod_10 = 0.0 site_10 1
# variable_mod_11 = 0.0 site_11 1
# variable_mod_12 = 0.0 site_12 1
# variable_mod_13 = 0.0 site_13 1
# variable_mod_14 = 0.0 site_14 1
# variable_mod_15 = 0.0 site_15 1
# variable_mod_16 = 0.0 site_16 1
```

**Comment by enryH** [comment]
I guess only the first two modifications are activated in that run? I think I should just ignore the lines which are comments.

**Comment by mlocardpaulet** [comment]
> I guess only the first two modifications are activated in that run? I think I should just ignore the lines which are comments. It might be that the information is also present in both files and I use the other one. `True` and `False` indicate which one is active.
> 
> So indeed, I take it from the `.workflow` FragPipe file, not the `.params` MSFragger one:
> 
> ```
> # fragpipe.workflow
> msfragger.table.fix-mods=0.0,C-Term Peptide,true,-1; 0.0,N-Term Peptide,true,-1; 0.0,C-Term Protein,true,-1; 0.0,N-Term Protein,true,-1; 0.0,G (glycine),true,-1; 0.0,A (alanine),true,-1; 0.0,S (serine),true,-1; 0.0,P (proline),true,-1; 0.0,V (valine),true,-1; 0.0,T (threonine),true,-1; 57.02146,C (cysteine),true,-1; 0.0,L (leucine),true,-1; 0.0,I (isoleucine),true,-1; 0.0,N (asparagine),true,-1; 0.0,D (aspartic acid),true,-1; 0.0,Q (glutamine),true,-1; 0.0,K (lysine),true,-1; 0.0,E (glutamic acid),true,-1; 0.0,M (methionine),true,-1; 0.0,H (histidine),true,-1; 0.0,F (phenylalanine),true,-1; 0.0,R (arginine),true,-1; 0.0,Y (tyrosine),true,-1; 0.0,W (tryptophan),true,-1; 0.0,B ,true,-1; 0.0,J,true,-1; 0.0,O,true,-1; 0.0,U,true,-1; 0.0,X,true,-1; 0.0,Z,true,-1
> msfragger.table.var-mods=15.9949,M,true,3; 42.0106,[^,true,1; 79.96633,STY,false,3; -17.0265,nQnC,false,1; -18.0106,nE,false,1; 4.025107,K,false,2; 6.020129,R,false,2; 8.014199,K,false,2; 10.008269,R,false,2; 0.0,site_10,false,1; 0.0,site_11,false,1; 0.0,site_12,false,1; 0.0,site_13,false,1; 0.0,site_14,false,1; 0.0,site_15,false,1; 0.0,site_16,false,1
> ```

thank you for clarifying. Looks good to me.

**Review by mlocardpaulet — APPROVED** [review]

**Pull request merged**
