### PR TITLE
:bug: Refactor saving of parameters file in DDA quant base module (#283)

### PR DESCRIPTION
**Pull request by enryH**
iRegaring Issue #283 
- regression: button now return a list due to FragPipe taking two parameter files (commit https://github.com/Proteobench/ProteoBench/commit/88ff9c845d768bca071f811ffee1608a58f191ef)
- regression: not re-submitting previously recorded runs, lead to an error for recording new runs (commit https://github.com/Proteobench/ProteoBench/commit/f81d3960ce85363ca1f9c3f71172f4976301c391)

### CODE REVIEW

**Comment by enryH** [comment]
@mlocardpaulet  Can you test it using your examples if possible? I think I could not re-submit an already existing run.

**Comment by mlocardpaulet** [comment]
> @mlocardpaulet Can you test it using your examples if possible? I think I could not re-submit an already existing run.

Thanks for working on this!
I tried it out and there is still an error message, and this time there is no pull request sent to proteobot: 
image

**Comment by mlocardpaulet** [comment]
> @mlocardpaulet Can you test it using your examples if possible? I think I could not re-submit an already existing run.

Thanks a lot for spending time on it!
I get an error, and there is no pull request sent to Proteobot... 
Do you want me to send you fake trimmed files? And/or I am happy to test it again whenever needed.

image

**Comment by enryH** [comment]
I also got this error and had to fix it locally. I thought it was due to not having the secrets define.

@RobbinBouwmeester @wolski Do we have a description of the logic of this module? I guess this file is the one you want to refactor for the UI?

**Comment by enryH** [comment]
Okay. The check was added some three months ago in this commit https://github.com/Proteobench/ProteoBench/commit/f81d3960ce85363ca1f9c3f71172f4976301c391.

I guess I will just deal with the error and find a fix.

**Comment by enryH** [comment]
Hmm. I think the current checks do not really work for local development and the culprit is this one global variable.

https://github.com/Proteobench/ProteoBench/blob/f33006c666ed60d81658409c2c2fcf78364032d7/webinterface/pages/DDA_Quant_ion.py#L25

Is this changed on the server? @julianu  

It effectively does not allow to go into the submit procedure.... I guess it is another regression due to this commit https://github.com/Proteobench/ProteoBench/commit/c597bd5eeb062f092830e49c5ba7ac239fe51641

**Comment by wolski** [comment]
@enryH 

LOCAL_DEVELOPMENT = False 
in the release 2.4

Can you set it to False or should I make the change and commit it into the branch?
Is this the only problem which prevents merging ths pull request?

**Review by wolski — COMMENTED** [review]
OK

**Review by wolski — APPROVED** [review]

**Pull request merged**
