### PR TITLE
Fix issue#122

### PR DESCRIPTION
**Pull request by mlocardpaulet**
I just added the ID so that we see it on hovering.

### CODE REVIEW

**Comment by mlocardpaulet** [comment]
It is just that the FDR at protein level, and some other information may not be the most interesting for this module. And I felt that the hovering box was a bit too big.

**Review by scaramonche — COMMENTED** [review]
Do you want to also change Search engine to be called Software tool?

**Comment by mlocardpaulet** [comment]
> Do you want to also change Search engine to be called Software tool?

Oh dear yes! I should. Thanks!

**Comment by mlocardpaulet** [comment]
Done!

**Review by wolski — APPROVED** [review]

**Pull request merged**
