### PR TITLE
:memo: Add current proteobench version to landing page of UI

### PR DESCRIPTION
**Pull request by enryH**

### CODE REVIEW

**Comment by mlocardpaulet** [comment]
It works when I run it locally. I have this in the main page:
image
My question is: why `0.2.7b0`?
It should be higher, no? 
In the CHANGELOG.md that I have, the head of the file is:
```
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [0.2.9] - 2024-05-21

...
```
Is this normal?

**Comment by mlocardpaulet** [comment]
Additional question: currently, when I click on the link to documentation from proteobench.cubimed, I reach the latest version. Can I just change the link to https://proteobench.readthedocs.io/en/stable/? Would you mind? This way it is consistent.

**Comment by julianu** [comment]
Actually, the last release (on GitHub) is 0.2.7, which is also installed on the server right now. On PyPi, there is 0.2.8b0, which seems a bit inconsistent.

**Comment by enryH** [comment]
I guess this is because there are only pre-releases on PyPI: https://pypi.org/project/proteobench/#history

setuptools-scm picks it up from the last tag/release in the repository.

@RobbinBouwmeester Do you know why?

We could also switch to a different PyPI release workflow if that is needed.

**Comment by enryH** [comment]
> Additional question: currently, when I click on the link to documentation from proteobench.cubimed, I reach the latest version. Can I just change the link to https://proteobench.readthedocs.io/en/stable/ in the home page? Would you mind? This way it is consistent.

The default version on readthedocs is the stable one: https://proteobench.readthedocs.io

So yes, go ahead

**Comment by enryH** [comment]
> It works when I run it locally. I have this in the main page: image My question is: why `0.2.7b0`? It should be higher, no? In the CHANGELOG.md that I have, the head of the file is:
> 
> ```
> # Changelog
> 
> All notable changes to this project will be documented in this file.
> 
> The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
> and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
> 
> ## [0.2.9] - 2024-05-21
> 
> ...
> ```
> 
> Is this normal?

So the answer is: The actions which is updating PyPI is failing: https://github.com/Proteobench/ProteoBench/actions/workflows/automated_release.yml

It complains about the `Changelog.md` file:

```
FATAL error reading changelog: changelog file does not contain version 0.2.9 
```

The build version is however `0.2.8`

```
Version number normalised: '0.2.8-beta' -> '0.2.8b0' (see PEP 440)
Successfully built proteobench-0.2.8b0-py3-none-any.whl
```

With the beta suffix.

So I guess we need to figure that out before on the main branch.

**Comment by enryH** [comment]
It added now also the intermediate version to the Changelog: https://github.com/Proteobench/ProteoBench/pull/315

**Comment by mlocardpaulet** [comment]
> > Additional question: currently, when I click on the link to documentation from proteobench.cubimed, I reach the latest version. Can I just change the link to https://proteobench.readthedocs.io/en/stable/ in the home page? Would you mind? This way it is consistent.
> 
> The default version on readthedocs is the stable one: https://proteobench.readthedocs.io
> 
> So yes, go ahead

done.

**Comment by enryH** [comment]
Then you can approve and merge:)

**Review by mlocardpaulet — APPROVED** [review]

**Pull request merged**
